//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrobit.Games.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Retrobit.Games.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _019cbea1_242c_40b7_b4bd_3e58495ecfaf {
            get {
                object obj = ResourceManager.GetObject("019cbea1-242c-40b7-b4bd-3e58495ecfaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _045d5800_989c_4bcd_9668_af30a204a5d3 {
            get {
                object obj = ResourceManager.GetObject("045d5800-989c-4bcd-9668-af30a204a5d3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _055b1d16_43ab_48be_8565_8ccedc8802d5 {
            get {
                object obj = ResourceManager.GetObject("055b1d16-43ab-48be-8565-8ccedc8802d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _07501be2_2019_40df_9043_2c393317d7e0 {
            get {
                object obj = ResourceManager.GetObject("07501be2-2019-40df-9043-2c393317d7e0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _081547e0_8308_45ab_9462_a28933cc7e7a {
            get {
                object obj = ResourceManager.GetObject("081547e0-8308-45ab-9462-a28933cc7e7a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0827b971_c2c8_4ba7_9313_0e51e75eb496 {
            get {
                object obj = ResourceManager.GetObject("_0827b971_c2c8_4ba7_9313_0e51e75eb496", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0af318b0_1ffc_401e_a2e0_8384b6231c8b {
            get {
                object obj = ResourceManager.GetObject("0af318b0-1ffc-401e-a2e0-8384b6231c8b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0bdcf9f7_572e_4311_b600_6a7cabdf9a0a {
            get {
                object obj = ResourceManager.GetObject("0bdcf9f7-572e-4311-b600-6a7cabdf9a0a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0e4dd70c_9f9e_4faa_8870_0e433bd4f231 {
            get {
                object obj = ResourceManager.GetObject("0e4dd70c-9f9e-4faa-8870-0e433bd4f231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0e4dd70c_9f9e_4faa_8870_0e433bd4f2311 {
            get {
                object obj = ResourceManager.GetObject("0e4dd70c-9f9e-4faa-8870-0e433bd4f2311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0e544972_3ac4_47d4_8c7a_eadc1bd1020f {
            get {
                object obj = ResourceManager.GetObject("_0e544972_3ac4_47d4_8c7a_eadc1bd1020f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0f1ff472_a800_471e_b99b_7ce9d672cbbb_jpg {
            get {
                object obj = ResourceManager.GetObject("0f1ff472-a800-471e-b99b-7ce9d672cbbb.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0f633ee3_5665_4128_a28b_9dfad23db4ff {
            get {
                object obj = ResourceManager.GetObject("_0f633ee3_5665_4128_a28b_9dfad23db4ff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1200px_245Suicune {
            get {
                object obj = ResourceManager.GetObject("1200px-245Suicune", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1200px_ALttP_Logo {
            get {
                object obj = ResourceManager.GetObject("1200px-ALttP_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1280px_NES_logo_svg {
            get {
                object obj = ResourceManager.GetObject("_1280px_NES_logo_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1280px_SNES_logo_svg {
            get {
                object obj = ResourceManager.GetObject("_1280px_SNES_logo_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1506865150998 {
            get {
                object obj = ResourceManager.GetObject("_1506865150998", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _16bit_link {
            get {
                object obj = ResourceManager.GetObject("16bit_link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _18e0af45_5df8_4867_b37a_13cda3e3a057 {
            get {
                object obj = ResourceManager.GetObject("18e0af45-5df8-4867-b37a-13cda3e3a057", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1a175c33_1c72_4524_bc46_9f88b566cb16 {
            get {
                object obj = ResourceManager.GetObject("1a175c33-1c72-4524-bc46-9f88b566cb16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1c8096c5_7af6_4dbd_a7e4_4df98c9c44fb {
            get {
                object obj = ResourceManager.GetObject("1c8096c5-7af6-4dbd-a7e4-4df98c9c44fb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1dd78885_5737_4671_9fda_91196de36818 {
            get {
                object obj = ResourceManager.GetObject("1dd78885-5737-4671-9fda-91196de36818", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1f9e7bad_5692_49b8_a438_232abe866541 {
            get {
                object obj = ResourceManager.GetObject("1f9e7bad-5692-49b8-a438-232abe866541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2358dcbf_dac9_4651_b396_f55cee9790b0 {
            get {
                object obj = ResourceManager.GetObject("2358dcbf-dac9-4651-b396-f55cee9790b0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _24d7a36c_3b0b_4eb4_a201_3075cf91ad9c {
            get {
                object obj = ResourceManager.GetObject("_24d7a36c_3b0b_4eb4_a201_3075cf91ad9c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _250px_006Charizard {
            get {
                object obj = ResourceManager.GetObject("250px-006Charizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _250px_384Rayquaza {
            get {
                object obj = ResourceManager.GetObject("250px-384Rayquaza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _263b14be_63d3_404a_a35b_7230897a7fcf {
            get {
                object obj = ResourceManager.GetObject("263b14be-63d3-404a-a35b-7230897a7fcf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2bacd72d_98b0_4ae5_a7a1_a05036c97904 {
            get {
                object obj = ResourceManager.GetObject("_2bacd72d_98b0_4ae5_a7a1_a05036c97904", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2ea26142_61e5_44fa_883b_e55c22043544 {
            get {
                object obj = ResourceManager.GetObject("_2ea26142_61e5_44fa_883b_e55c22043544", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2gsjgna1uruvUuS7ndh9YqVwYGPLVszbFLwwpAYXZyHFKtHTof7Xzn6JDKEZ5WFpZZ26hNuanYJ4pLfv1ttVPV2pt6YKTbofJWoZAqvj7KqH5ayQDb {
            get {
                object obj = ResourceManager.GetObject("2gsjgna1uruvUuS7ndh9YqVwYGPLVszbFLwwpAYXZyHFKtHTof7Xzn6JDKEZ5WFpZZ26hNuanYJ4pLfv1" +
                        "ttVPV2pt6YKTbofJWoZAqvj7KqH5ayQDb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _300px_ALttP_Logo {
            get {
                object obj = ResourceManager.GetObject("300px-ALttP_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _300px_TAoL_Black_Logo {
            get {
                object obj = ResourceManager.GetObject("300px-TAoL_Black_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _335880f8_1db7_4b9c_b918_0d168d01fec5 {
            get {
                object obj = ResourceManager.GetObject("335880f8-1db7-4b9c-b918-0d168d01fec5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _33aaa5f8_d8bb_4cf8_b7fd_b39a5759b53f_png {
            get {
                object obj = ResourceManager.GetObject("33aaa5f8-d8bb-4cf8-b7fd-b39a5759b53f.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _35a3d0f0_461d_4ee0_8afa_df5d1b753a99 {
            get {
                object obj = ResourceManager.GetObject("35a3d0f0-461d-4ee0-8afa-df5d1b753a99", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _38___Yoshi_games_play_fun__512 {
            get {
                object obj = ResourceManager.GetObject("38_-_Yoshi_games_play_fun_-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _384da923_15ea_44f2_9d07_16c996b63aaa {
            get {
                object obj = ResourceManager.GetObject("384da923-15ea-44f2-9d07-16c996b63aaa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _396e4974_d018_4d02_8ec7_3c2759ef5843 {
            get {
                object obj = ResourceManager.GetObject("_396e4974_d018_4d02_8ec7_3c2759ef5843", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3D_Classics_Kid_Icarus {
            get {
                object obj = ResourceManager.GetObject("3D_Classics_Kid_Icarus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3d581f4c_0c1b_42d1_bfac_9542b3b4ae98 {
            get {
                object obj = ResourceManager.GetObject("_3d581f4c_0c1b_42d1_bfac_9542b3b4ae98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3fdfea06_890f_49b7_9a3e_248fea26def2 {
            get {
                object obj = ResourceManager.GetObject("3fdfea06-890f-49b7-9a3e-248fea26def2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _40a6e33a_a1d8_4226_9e9b_5398226156e2 {
            get {
                object obj = ResourceManager.GetObject("40a6e33a-a1d8-4226-9e9b-5398226156e2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _41448c94_cc89_41a7_b77d_673701608517 {
            get {
                object obj = ResourceManager.GetObject("41448c94-cc89-41a7-b77d-673701608517", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _437ad260_785b_479e_ba1b_0b7b079e4094 {
            get {
                object obj = ResourceManager.GetObject("_437ad260_785b_479e_ba1b_0b7b079e4094", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4503d0f6_3dad_4dfd_8ab5_54be64130f4d {
            get {
                object obj = ResourceManager.GetObject("4503d0f6-3dad-4dfd-8ab5-54be64130f4d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _47d92511_6554_49ca_ab1c_c5986d05db16 {
            get {
                object obj = ResourceManager.GetObject("47d92511-6554-49ca-ab1c-c5986d05db16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4a036083_b5c7_4d0e_8d33_d45a567f34b7 {
            get {
                object obj = ResourceManager.GetObject("4a036083-b5c7-4d0e-8d33-d45a567f34b7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _502e9319_c887_453f_a291_6852a334d657 {
            get {
                object obj = ResourceManager.GetObject("_502e9319_c887_453f_a291_6852a334d657", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _52b8fb58_017b_4273_adaa_f3cb823529b0 {
            get {
                object obj = ResourceManager.GetObject("_52b8fb58_017b_4273_adaa_f3cb823529b0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5331305289b6807640009bd6b4c89d0a {
            get {
                object obj = ResourceManager.GetObject("5331305289b6807640009bd6b4c89d0a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _57cd5c59_69fe_4541_ab4e_d604bf5aeb32 {
            get {
                object obj = ResourceManager.GetObject("_57cd5c59_69fe_4541_ab4e_d604bf5aeb32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5e7af8c2_be30_4a7a_850b_c48461490cf4 {
            get {
                object obj = ResourceManager.GetObject("_5e7af8c2_be30_4a7a_850b_c48461490cf4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _67080b03_6fee_4761_adc4_abd87842a4d2 {
            get {
                object obj = ResourceManager.GetObject("67080b03-6fee-4761-adc4-abd87842a4d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _685408c1_698f_4a97_91e6_0aa1fa567241 {
            get {
                object obj = ResourceManager.GetObject("685408c1-698f-4a97-91e6-0aa1fa567241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6cb6058b_0215_47cf_9691_af3e78ce23a6 {
            get {
                object obj = ResourceManager.GetObject("6cb6058b-0215-47cf-9691-af3e78ce23a6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6d4eee5b_4a18_426a_8c90_55203923c246 {
            get {
                object obj = ResourceManager.GetObject("6d4eee5b-4a18-426a-8c90-55203923c246", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6f4cb84e_43ce_4b42_88dc_593c994377f1 {
            get {
                object obj = ResourceManager.GetObject("6f4cb84e-43ce-4b42-88dc-593c994377f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6fbccea3_2146_46bf_bf62_3784e834e1ff {
            get {
                object obj = ResourceManager.GetObject("6fbccea3-2146-46bf-bf62-3784e834e1ff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _726d8929_5015_4a94_ace2_da43e9d935c5 {
            get {
                object obj = ResourceManager.GetObject("_726d8929_5015_4a94_ace2_da43e9d935c5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _76544f7b_a881_4a4a_83ec_721b9bdef3c1 {
            get {
                object obj = ResourceManager.GetObject("76544f7b-a881-4a4a-83ec-721b9bdef3c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7f1cd22b_5f8e_47bd_b5ad_eb3ec0bf2a13 {
            get {
                object obj = ResourceManager.GetObject("7f1cd22b-5f8e-47bd-b5ad-eb3ec0bf2a13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _81c03bcd_6311_4116_9b38_ed762744e933 {
            get {
                object obj = ResourceManager.GetObject("81c03bcd-6311-4116-9b38-ed762744e933", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8aa352d1_899d_4e1a_8236_d1caf2e50ed2 {
            get {
                object obj = ResourceManager.GetObject("8aa352d1-899d-4e1a-8236-d1caf2e50ed2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8c1a9e22_0d0d_4e44_a32e_b50199df8a55 {
            get {
                object obj = ResourceManager.GetObject("8c1a9e22-0d0d-4e44-a32e-b50199df8a55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8ce6bc0a_553c_4af5_8d3d_126c5ae1dc22 {
            get {
                object obj = ResourceManager.GetObject("_8ce6bc0a_553c_4af5_8d3d_126c5ae1dc22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _90cf2517_1ef8_49bd_866c_a2d2b7b5d1a4 {
            get {
                object obj = ResourceManager.GetObject("90cf2517-1ef8-49bd-866c-a2d2b7b5d1a4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _91c408e4833006eb93d33d23587e561e {
            get {
                object obj = ResourceManager.GetObject("91c408e4833006eb93d33d23587e561e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _96d86e0c_e80f_43f3_82f9_3fbadf389ab0 {
            get {
                object obj = ResourceManager.GetObject("96d86e0c-e80f-43f3-82f9-3fbadf389ab0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _98cebfcf_1a08_435f_bdcc_27e47073f205 {
            get {
                object obj = ResourceManager.GetObject("98cebfcf-1a08-435f-bdcc-27e47073f205", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9d530b2c_f042_4dbd_b8be_ff1a9914bc71 {
            get {
                object obj = ResourceManager.GetObject("9d530b2c-f042-4dbd-b8be-ff1a9914bc71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9e0 {
            get {
                object obj = ResourceManager.GetObject("9e0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _chat_alert_512 {
            get {
                object obj = ResourceManager.GetObject("_chat_alert_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap a530156e_0ecc_48d5_8920_22f6c4b7db8e {
            get {
                object obj = ResourceManager.GetObject("a530156e-0ecc-48d5-8920-22f6c4b7db8e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap a9e792fb75ef894 {
            get {
                object obj = ResourceManager.GetObject("a9e792fb75ef894", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap aa1be922_249b_46df_99f2_459a475d864f {
            get {
                object obj = ResourceManager.GetObject("aa1be922-249b-46df-99f2-459a475d864f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap albw_hylian_shield_v2_by_blueamnesiac_d7harvu {
            get {
                object obj = ResourceManager.GetObject("albw_hylian_shield_v2_by_blueamnesiac_d7harvu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap b4c002be_d127_4c93_afd5_3f656183ea9b {
            get {
                object obj = ResourceManager.GetObject("b4c002be-d127-4c93-afd5-3f656183ea9b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap b68a54a4_ece1_4f62_a93f_be07b7a61379 {
            get {
                object obj = ResourceManager.GetObject("b68a54a4-ece1-4f62-a93f-be07b7a61379", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap banjo_kazooie_and_yooka_laylee_by_banjo2015_d8rwds_by_princesseninka_daihcs0 {
            get {
                object obj = ResourceManager.GetObject("banjo_kazooie_and_yooka_laylee_by_banjo2015_d8rwds_by_princesseninka_daihcs0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Banjo_kazooie_logo {
            get {
                object obj = ResourceManager.GetObject("Banjo_kazooie_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap banjo_kazooie_logo_3d_render_by_dreams_n_nightmares_d603urg {
            get {
                object obj = ResourceManager.GetObject("banjo_kazooie_logo_3d_render_by_dreams_n_nightmares_d603urg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Banjo_TooieLogo {
            get {
                object obj = ResourceManager.GetObject("Banjo-TooieLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BanjoKazooieTooie5 {
            get {
                object obj = ResourceManager.GetObject("BanjoKazooieTooie5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bc942bdf_d6a2_4292_8edd_4eb44efee8fd_jpg {
            get {
                object obj = ResourceManager.GetObject("bc942bdf-d6a2-4292-8edd-4eb44efee8fd.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bf7969a7_a0dc_4e94_87f0_5edc8996538c {
            get {
                object obj = ResourceManager.GetObject("bf7969a7-a0dc-4e94-87f0-5edc8996538c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Black_on_Transparent {
            get {
                object obj = ResourceManager.GetObject("Black_on_Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap c0cfa5ca_0b5a_40e8_a94c_42ff9741e312 {
            get {
                object obj = ResourceManager.GetObject("c0cfa5ca-0b5a-40e8-a94c-42ff9741e312", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap c5a08c70_9bcd_4cd7_96d7_df2c4f82bc2b {
            get {
                object obj = ResourceManager.GetObject("c5a08c70-9bcd-4cd7-96d7-df2c4f82bc2b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap c712dd7d_db08_4b1e_a057_927fe054cee4 {
            get {
                object obj = ResourceManager.GetObject("c712dd7d-db08-4b1e-a057-927fe054cee4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Castlevania_logo_color {
            get {
                object obj = ResourceManager.GetObject("Castlevania_logo_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CastlevaniaSymbol {
            get {
                object obj = ResourceManager.GetObject("CastlevaniaSymbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cbc53d45_745b_41a5_a08b_73dd2ad93d1c {
            get {
                object obj = ResourceManager.GetObject("cbc53d45-745b-41a5-a08b-73dd2ad93d1c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cf86a691_49bc_448d_b8d2_335f328449f0 {
            get {
                object obj = ResourceManager.GetObject("cf86a691-49bc-448d-b8d2-335f328449f0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Chrono_Trigger_Logo {
            get {
                object obj = ResourceManager.GetObject("Chrono_Trigger_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap com_stam_guidehervestmoon {
            get {
                object obj = ResourceManager.GetObject("com.stam.guidehervestmoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Conker_Bigger_Bad_Fur_Day_Logo_Final {
            get {
                object obj = ResourceManager.GetObject("Conker_Bigger_Bad_Fur_Day_Logo_Final", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap conker_s_bad_fur_day_by_pooterman_db5dbyb {
            get {
                object obj = ResourceManager.GetObject("conker_s_bad_fur_day_by_pooterman-db5dbyb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap d54ea3d5_440e_4659_96d5_3f3dd6a123f2 {
            get {
                object obj = ResourceManager.GetObject("d54ea3d5-440e-4659-96d5-3f3dd6a123f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap d772fa65_e0de_409f_b52e_e0e7d65c4fe7 {
            get {
                object obj = ResourceManager.GetObject("d772fa65-e0de-409f-b52e-e0e7d65c4fe7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap df436972_2e5c_4525_8c0c_82c4b77be5b3 {
            get {
                object obj = ResourceManager.GetObject("df436972-2e5c-4525-8c0c-82c4b77be5b3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Diddy_Kong_Racing_logo {
            get {
                object obj = ResourceManager.GetObject("Diddy_Kong_Racing_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DK_DK {
            get {
                object obj = ResourceManager.GetObject("DK_DK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dokey_Kong_Country_donkey_kong_1101000_213_236 {
            get {
                object obj = ResourceManager.GetObject("Dokey-Kong-Country-donkey-kong-1101000_213_236", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Donkey_Kong_arcade_logo {
            get {
                object obj = ResourceManager.GetObject("Donkey_Kong_arcade_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Donkey_Kong_Artwork___Donkey_Kong_64 {
            get {
                object obj = ResourceManager.GetObject("Donkey_Kong_Artwork_-_Donkey_Kong_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Donkey_Kong_Country_2_Diddy_Kong_Quest {
            get {
                object obj = ResourceManager.GetObject("Donkey_Kong_Country_2_Diddy_Kong_Quest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Donkey_Kong_Country_logo {
            get {
                object obj = ResourceManager.GetObject("Donkey_Kong_Country_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dr__Mario_Icon {
            get {
                object obj = ResourceManager.GetObject("Dr._Mario_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dr_Mario_logo {
            get {
                object obj = ResourceManager.GetObject("Dr_Mario_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap e234e09b_62b9_4c0b_8cd8_7a2a12134dc2 {
            get {
                object obj = ResourceManager.GetObject("e234e09b_62b9_4c0b_8cd8_7a2a12134dc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap e92fe3421ccfa39212722e984c06e0b490d9f8e3_00 {
            get {
                object obj = ResourceManager.GetObject("e92fe3421ccfa39212722e984c06e0b490d9f8e3_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap e96de88c_338a_490b_a664_dea3a636cf1c {
            get {
                object obj = ResourceManager.GetObject("e96de88c-338a-490b-a664-dea3a636cf1c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap eff8a63e_272b_47fc_8a2a_d6905df2b330 {
            get {
                object obj = ResourceManager.GetObject("eff8a63e-272b-47fc-8a2a-d6905df2b330", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap excitebike_2 {
            get {
                object obj = ResourceManager.GetObject("excitebike_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap f_zero__snes__by_pooterman_dangsju {
            get {
                object obj = ResourceManager.GetObject("f_zero__snes__by_pooterman-dangsju", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap F_Zero_icon {
            get {
                object obj = ResourceManager.GetObject("F-Zero_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap F_Zero_logo {
            get {
                object obj = ResourceManager.GetObject("F-Zero_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap f0760be3_acfe_49d0_8084_f6ff2508af2c {
            get {
                object obj = ResourceManager.GetObject("f0760be3-acfe-49d0-8084-f6ff2508af2c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap f50ff361_ed6d_4877_ab98_f85c2037efc3 {
            get {
                object obj = ResourceManager.GetObject("f50ff361-ed6d-4877-ab98-f85c2037efc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap f5f5ede1330e54b600248c9ac5c88a19 {
            get {
                object obj = ResourceManager.GetObject("f5f5ede1330e54b600248c9ac5c88a19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap f88916aa_e75c_4f09_bb40_e3ff07665a55 {
            get {
                object obj = ResourceManager.GetObject("f88916aa-e75c-4f09-bb40-e3ff07665a55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fb6412ac_5bcc_43ce_9fd2_82b6f7ed3ff3 {
            get {
                object obj = ResourceManager.GetObject("fb6412ac-5bcc-43ce-9fd2-82b6f7ed3ff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fd6c1956ba89b2cdbc348d810071cd57_icon {
            get {
                object obj = ResourceManager.GetObject("fd6c1956ba89b2cdbc348d810071cd57_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fe7e8b2cd007d2e73870a0579b06c354__requests_post_eye_logo {
            get {
                object obj = ResourceManager.GetObject("fe7e8b2cd007d2e73870a0579b06c354--requests-post-eye-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ghosts_n_Goblins_Logo {
            get {
                object obj = ResourceManager.GetObject("Ghosts-n-Goblins-Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gifs_ninja_gaiden_avatar {
            get {
                object obj = ResourceManager.GetObject("gifs_ninja-gaiden_avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Goldeneye_007_Logo {
            get {
                object obj = ResourceManager.GetObject("Goldeneye_007_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ice_Climber_Classics {
            get {
                object obj = ResourceManager.GetObject("Ice_Climber_Classics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_issue15supermariobros3 {
            get {
                object obj = ResourceManager.GetObject("icon_issue15supermariobros3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap index {
            get {
                object obj = ResourceManager.GetObject("index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap index1 {
            get {
                object obj = ResourceManager.GetObject("index1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kid_Icarus_Universe_Icon {
            get {
                object obj = ResourceManager.GetObject("Kid_Icarus_Universe_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kirby_s_Adventure_logo {
            get {
                object obj = ResourceManager.GetObject("Kirby\'s_Adventure_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kisspng_computer_icons_shutdown_button_logo_power_5abd365d4a86d2_7214086015223496613053 {
            get {
                object obj = ResourceManager.GetObject("kisspng_computer_icons_shutdown_button_logo_power_5abd365d4a86d2_7214086015223496" +
                        "613053", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kisspng_mario_kart_wii_mario_bros_toad_automobile_mechanic_5ada63019181b6_788689181524261633596 {
            get {
                object obj = ResourceManager.GetObject("kisspng-mario-kart-wii-mario-bros-toad-automobile-mechanic-5ada63019181b6.7886891" +
                        "81524261633596", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kisspng_window_princess_peach_stained_glass_super_mario_64_watercolor_stain_5ac9f779d131d0_8647173515231855298569 {
            get {
                object obj = ResourceManager.GetObject("kisspng_window_princess_peach_stained_glass_super_mario_64_watercolor_stain_5ac9f" +
                        "779d131d0_8647173515231855298569", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Link_and_the_Rod_of_Seasons {
            get {
                object obj = ResourceManager.GetObject("Link_and_the_Rod_of_Seasons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap link_sprite_cutout {
            get {
                object obj = ResourceManager.GetObject("link_sprite_cutout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOADING {
            get {
                object obj = ResourceManager.GetObject("LOADING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_EN___Pokemon_Crystal {
            get {
                object obj = ResourceManager.GetObject("Logo_EN_-_Pokemon_Crystal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_GBC {
            get {
                object obj = ResourceManager.GetObject("Logo-GBC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_star_fox_2 {
            get {
                object obj = ResourceManager.GetObject("Logo-star-fox-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logoarm {
            get {
                object obj = ResourceManager.GetObject("Logoarm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap majora_mask {
            get {
                object obj = ResourceManager.GetObject("majora_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap majora_s_mask_logo_by_blueamnesiac_d7f83th {
            get {
                object obj = ResourceManager.GetObject("majora_s_mask_logo_by_blueamnesiac_d7f83th", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario {
            get {
                object obj = ResourceManager.GetObject("mario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mario_and_Luigi_22 {
            get {
                object obj = ResourceManager.GetObject("Mario_and_Luigi_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mario_and_Luigi_Superstar_Saga_Logo {
            get {
                object obj = ResourceManager.GetObject("Mario_and_Luigi_Superstar_Saga_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario_kart_64_logo_by_ringostarr39_d63zk4p {
            get {
                object obj = ResourceManager.GetObject("mario_kart_64_logo_by_ringostarr39-d63zk4p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario_kart_icon_by_betatus_d6th2q4 {
            get {
                object obj = ResourceManager.GetObject("mario_kart_icon_by_betatus-d6th2q4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mario_Kart_Super_Circuit_logo {
            get {
                object obj = ResourceManager.GetObject("Mario_Kart_Super_Circuit_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario_party_icon {
            get {
                object obj = ResourceManager.GetObject("mario-party-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario1 {
            get {
                object obj = ResourceManager.GetObject("mario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario2 {
            get {
                object obj = ResourceManager.GetObject("mario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario64bp_by_yoshiyaki_d9xldr4 {
            get {
                object obj = ResourceManager.GetObject("mario64bp_by_yoshiyaki_d9xldr4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mega_man_x_logo_by_ringostarr39_d8bs36r {
            get {
                object obj = ResourceManager.GetObject("mega_man_x_logo_by_ringostarr39-d8bs36r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap megaman_x_icon_by_xxsh4kzxx_d5h0znk {
            get {
                object obj = ResourceManager.GetObject("megaman_x_icon_by_xxsh4kzxx-d5h0znk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap metroid_9_320744 {
            get {
                object obj = ResourceManager.GetObject("metroid-9-320744", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap metroid_9_3207441 {
            get {
                object obj = ResourceManager.GetObject("metroid-9-3207441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Metroid_Fusion_Logo {
            get {
                object obj = ResourceManager.GetObject("Metroid_Fusion_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Metroid_Title {
            get {
                object obj = ResourceManager.GetObject("Metroid_Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap metroidzm_13_hd {
            get {
                object obj = ResourceManager.GetObject("metroidzm_13_hd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mk {
            get {
                object obj = ResourceManager.GetObject("mk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MPLogo {
            get {
                object obj = ResourceManager.GetObject("MPLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MTO_Donkey_Kong_Icon {
            get {
                object obj = ResourceManager.GetObject("MTO_Donkey_Kong_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nintendo_64_logo_1024x308 {
            get {
                object obj = ResourceManager.GetObject("nintendo_64_logo_1024x308", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ocarina_of_time_logo_by_blueamnesiac_d7f83kw {
            get {
                object obj = ResourceManager.GetObject("ocarina_of_time_logo_by_blueamnesiac_d7f83kw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Oracle_of_Ages_Logo {
            get {
                object obj = ResourceManager.GetObject("Oracle_of_Ages_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap p6z4 {
            get {
                object obj = ResourceManager.GetObject("p6z4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Paper_Mario_icon {
            get {
                object obj = ResourceManager.GetObject("Paper-Mario-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Paper_Mario_Logo {
            get {
                object obj = ResourceManager.GetObject("Paper_Mario_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Perfect_Dark_logo {
            get {
                object obj = ResourceManager.GetObject("Perfect_Dark_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ph03nyx_Super_Mario_Retro_Flower_Fire_2 {
            get {
                object obj = ResourceManager.GetObject("Ph03nyx-Super-Mario-Retro-Flower-Fire-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ph03nyx_Super_Mario_Yoshis_Egg {
            get {
                object obj = ResourceManager.GetObject("Ph03nyx-Super-Mario-Yoshis-Egg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pokemon_FireRed_logo {
            get {
                object obj = ResourceManager.GetObject("Pokemon_FireRed_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pokemon_go_play_game_charcter_512 {
            get {
                object obj = ResourceManager.GetObject("pokemon_go_play_game_charcter-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PokémonEmerald {
            get {
                object obj = ResourceManager.GetObject("PokémonEmerald", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Punch_Out___Universe_Icon {
            get {
                object obj = ResourceManager.GetObject("Punch-Out!!_Universe_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Punchout_Arcade_Logo {
            get {
                object obj = ResourceManager.GetObject("Punchout_Arcade_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap punchout_marquee {
            get {
                object obj = ResourceManager.GetObject("punchout_marquee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pyellow {
            get {
                object obj = ResourceManager.GetObject("pyellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rare_logo {
            get {
                object obj = ResourceManager.GetObject("Rare_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Red_Nose_Transparent {
            get {
                object obj = ResourceManager.GetObject("Red_Nose_Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Retro_Flower_Yoshi_icon {
            get {
                object obj = ResourceManager.GetObject("Retro-Flower-Yoshi-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap secret_of_mana___circle_by_taricalmcacil_d2f6am2 {
            get {
                object obj = ResourceManager.GetObject("secret_of_mana___circle_by_taricalmcacil-d2f6am2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Secret_of_Mana_Logo_Transparent {
            get {
                object obj = ResourceManager.GetObject("Secret_of_Mana_Logo_Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sega_genesis_logo {
            get {
                object obj = ResourceManager.GetObject("Sega_genesis_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap setting_512 {
            get {
                object obj = ResourceManager.GetObject("setting_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Shantae_icons_square_girl {
            get {
                object obj = ResourceManager.GetObject("Shantae_icons_square_girl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Símbolo_Smash {
            get {
                object obj = ResourceManager.GetObject("Símbolo_Smash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SMash_Icon {
            get {
                object obj = ResourceManager.GetObject("SMash_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Star_Fox_64_logo {
            get {
                object obj = ResourceManager.GetObject("Star_Fox_64_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StarFox_icon {
            get {
                object obj = ResourceManager.GetObject("StarFox_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StarFox_lOgO {
            get {
                object obj = ResourceManager.GetObject("StarFox_lOgO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StarFoxSymbolSSBV {
            get {
                object obj = ResourceManager.GetObject("StarFoxSymbolSSBV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap super_dodgeball_nes_logo {
            get {
                object obj = ResourceManager.GetObject("super-dodgeball-nes-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Mario_64 {
            get {
                object obj = ResourceManager.GetObject("Super_Mario_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Mario_Bros__Logo_svg {
            get {
                object obj = ResourceManager.GetObject("Super_Mario_Bros._Logo.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Mario_Bros__Logo1 {
            get {
                object obj = ResourceManager.GetObject("Super_Mario_Bros._Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_mario_bros_2_logo_by_ringostarr39_d5c6owz {
            get {
                object obj = ResourceManager.GetObject("Super_mario_bros_2_logo_by_ringostarr39-d5c6owz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_mario_bros_3_seeklogo_com {
            get {
                object obj = ResourceManager.GetObject("Super-mario-bros-3-seeklogo_com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Mario_Kart_Logo {
            get {
                object obj = ResourceManager.GetObject("Super-Mario-Kart-Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Mario_RPG_Logo {
            get {
                object obj = ResourceManager.GetObject("Super_Mario_RPG_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Mario_World_2_Yoshi_s_Island_Logo {
            get {
                object obj = ResourceManager.GetObject("Super_Mario_World_2_Yoshi\'s_Island_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap super_mario_world_by_mestrenorax {
            get {
                object obj = ResourceManager.GetObject("super_mario_world_by_mestrenorax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Metroid_logo {
            get {
                object obj = ResourceManager.GetObject("Super_Metroid_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_punch_out_logo_by_ringostarr39_d7nnm37 {
            get {
                object obj = ResourceManager.GetObject("Super_punch_out_logo_by_ringostarr39-d7nnm37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Smash_Bros___N64__logo {
            get {
                object obj = ResourceManager.GetObject("Super_Smash_Bros._(N64)_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Super_Smash_Bros1 {
            get {
                object obj = ResourceManager.GetObject("Super_Smash_Bros1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SuperMarioWorld_Logo {
            get {
                object obj = ResourceManager.GetObject("SuperMarioWorld_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SurvivalKids_Title_EU {
            get {
                object obj = ResourceManager.GetObject("SurvivalKids_Title_EU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tetris_worlds {
            get {
                object obj = ResourceManager.GetObject("tetris-worlds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap The_Legend_of_Zelda___Link_s_Awakening_DX__logo_ {
            get {
                object obj = ResourceManager.GetObject("The_Legend_of_Zelda_-_Link\'s_Awakening_DX_(logo)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TLOZ {
            get {
                object obj = ResourceManager.GetObject("TLOZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TMC_Ezlo_Artwork {
            get {
                object obj = ResourceManager.GetObject("TMC_Ezlo_Artwork", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap triforce_icon_600x520 {
            get {
                object obj = ResourceManager.GetObject("triforce-icon-600x520", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tumblr_oa20wbh97D1uot2dco3_500 {
            get {
                object obj = ResourceManager.GetObject("tumblr_oa20wbh97D1uot2dco3_500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Wario_Land_3_Logo {
            get {
                object obj = ResourceManager.GetObject("Wario_Land_3_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Wario_SR_Icon {
            get {
                object obj = ResourceManager.GetObject("Wario_SR_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WarioWare___Logo {
            get {
                object obj = ResourceManager.GetObject("WarioWare_-_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Wariowarebomb {
            get {
                object obj = ResourceManager.GetObject("Wariowarebomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap website {
            get {
                object obj = ResourceManager.GetObject("website", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Yoshi_logo {
            get {
                object obj = ResourceManager.GetObject("Yoshi_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap YS_Sniff {
            get {
                object obj = ResourceManager.GetObject("YS_Sniff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
